### PR TITLE
Add support for MacOS 

### LINKED ISSUE #7: support for macOS
I encountered the `dlopen failed` error when using this package on macOS. Although I fixed it by modifying `self._handle = DLHandle(".magic/envs/default/lib/libSDL2.so")` to `self._handle = DLHandle(".magic/envs/default/lib/libSDL2.dylib")` in `_sdl.mojo` at line #338, it would be good to see a better support for macOS.

### PR DESCRIPTION
**Pull request by shivasankarka**
- Added libSDL2 support for MacOS by including libSDL2.dylib in search path.
- formatted all files

Resolves #7

### CODE REVIEW

**Comment by helehex** [comment]
Glad we can get this working finally.

**Comment by Ryul0rd** [comment]
Hey thanks for this. Can you add `@parameter` and `constrained` to the checks to make them known at comptime so they don't need to raise?

**Comment by helehex** [comment]
IIRC, this was actually working before (we were branching the path based on os in the same way), but regressed when we switched to magic

**Comment by helehex** [comment]
we still don't have any guidelines around formatting, i suggest standard mojo format at 100 columns to make things easy, but it's up to Ryul0rd

**Comment by helehex** [comment]
or maybe even use a really high column count for now so that it doesn't split lines

**Comment by shivasankarka** [comment]
@Ryul0rd Alright, I'll make the changes. 
@helehex I just used the default mojo formatter for this.

**Comment by helehex** [comment]
@shivasankarka i suggest doing `mojo format -l 1000` for now, but like is said it's up to @Ryul0rd

**Comment by shivasankarka** [comment]
@helehex I have moved the conditions to comp time and formatted using the command you provided.

**Pull request merged**
